spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/product/**
        - id: category-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/category/**
        - id: inventory-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/inventory/**
        - id: message-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/messages/**
        - id: customer-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/customer/**
        - id: user-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/user/**
        - id: carts-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/cart/**
        - id: payment-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/payment-methods/**
        - id: billing-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/billing/**
        - id: minio-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/files/**
        - id: email-service
          uri: http://localhost:9001
          predicates:
            - Path=/api/email/**
        - id: payment-history-service
          uri: http://localhost:8095
          predicates:
            - Path=/api/payment-history/**